flags: {}
packages:
- '.'
extra-deps:
- aeson-1.2.1.0
- base-orphans-0.6
- base-prelude-1.2.0.1
- imap-0.3.0.2
- mmorph-1.1.0
- primitive-0.6.2.0
- rolling-queue-0.1
- semigroupoids-5.2
- vector-0.12.0.1
resolver: lts-8.19
